#!/bin/bash
# Vercel Deployment Commands for Pausely

echo "🚀 Pausely Vercel Deployment"
echo "============================"
echo ""
echo "Step 1: Login to Vercel (if needed)"
echo "  vercel login"
echo ""
echo "Step 2: Link project"
echo "  vercel link"
echo "  When asked for directory, enter: apps/web"
echo ""
echo "Step 3: Add environment variables"
echo "  vercel env add DATABASE_URL"
echo "  vercel env add JWT_SECRET"
echo "  vercel env add JWT_REFRESH_SECRET"
echo "  vercel env add OPENAI_API_KEY"
echo "  vercel env add STRIPE_SECRET_KEY"
echo "  vercel env add STRIPE_WEBHOOK_SECRET"
echo "  vercel env add NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "  vercel env add STRIPE_PREMIUM_PRICE_ID"
echo ""
echo "Step 4: Deploy"
echo "  vercel --prod"
echo ""
echo "Step 5: Run database migrations"
echo "  cd packages/db"
echo "  vercel env pull .env.production"
echo "  source .env.production"
echo "  pnpm migrate:deploy"
echo ""
